### ISSUE TITLE
Unable to load kernel

### ISSUE THREAD

**Issue by Pascal-Ortiz** [akabe/ocaml-jupyter#101]
Hi
I have installed ocaml-jupyter on my fresh version of Ubuntu 18.04. Before installing, I have a previous installation of jupyter notebook. 

The problem I face is the following : Jupyter Notebook is unable to connect permantly to the kernel. I get repeatedly the message:

Fatal error: cannot load shared library dlllwt_unix_stubs
Reason: dlllwt_unix_stubs.so: cannot open shared object file: No such file or directory

By the way, the shared library has been installed by opam in my ~/.opam/system/lib/stublibs/ folder.

Thanks for any hint.

**Comment by Pascal-Ortiz** [comment]
After rebooting, the problem seems to be fixed so far and ocaml-jupyter is working!

**Comment by akabe** [comment]
@Pascal-Ortiz Does the problem appear after the rebooting?

**Comment by Pascal-Ortiz** [comment]
It doesn't: seems you need to reboot the system.

I got a similar problem (Fatal error: cannot load shared library dlllwt_unix_stubs) installing ocaml-jupyter under Windows 10 by means of the Windows Subsystem for Linux. The script [HERE](http://pascal.ortiz.free.fr/contents/autres/jupyter_ocaml/jupyter_ocaml.html#le-script-d-installation) worked for me (sorry, it's in french).

**Comment by akabe** [comment]
Does `mkdir .local/share/jupyter` solve this problem?

I think `LD_LIBRARY_PATH` and/or `CAML_LD_LIBRARY_PATH` are wrong. `eval $(opam config env)` or manual setting solves maybe:

```
export LD_LIBRARY_PATH=$(opam config var stublibs)
export CAML_LD_LIBRARY_PATH=$(opam config var stublibs)
```

**Comment by Pascal-Ortiz** [comment]
> Does `mkdir .local/share/jupyter` solve this problem?
> 

Yes, it solves the problem. Not making the directory  raises an error when I try to open an ocaml worksheet:

Unexpected error while saving file: Untitled.ipynb [Errno 13] Permission denied: '/home/po/.local/share/jupyter/notebook_secret'

In order to get it right, I did: **sudo chmod -R 777  jupyter/** and this worked fine.

**Comment by akabe** [comment]
Thanks. I cannot reproduce the error, but your solution is probably useful for other users. I will write about the problem into Wiki.
