### ISSUE TITLE
Passing additional parameters to OCaml

### ISSUE THREAD

**Issue by ysalmon** [akabe/ocaml-jupyter#102]
Greetings,

I am just starting to look into using Jupyter and your kernel instead of Emacs+Tuareg for my introductory course.

I am using [Arthur Charguéraud's kernel fork](https://github.com/charguer/ocaml/tree/4.02.2+improved-errors) (based on 4.02.2) which supports better error messages.

I was able to install your kernel under the appropriate opam switch but I have to pass option ```-easy-type-errors``` to ocaml in order to activate the better messages.

How can I do this ? Adding the option to argv in the json does not work as the kernel does not recognise the option.

**Comment by akabe** [comment]
Oops. https://github.com/charguer/ocaml is too old: this kernel requires 4.04, or above.

**Comment by ysalmon** [comment]
Well, it seems to "just work" ;-)
![screenshot_20181006_215823](https://user-images.githubusercontent.com/536850/46575280-00875c00-c9b3-11e8-9a6b-b497ce180162.png)

**Comment by ysalmon** [comment]
Indeed ; this was 2.3.0.

I will see if a port of Cahrguéraud's patches to a newer release is possible (I would like it for other reasons).

Anyway, the ability to pass parameters would be nice for other use cases as well, I think.

**Comment by akabe** [comment]
I can implement additional parameters, but I cannot test it without a customized ocaml compiler. Can you port the patches to a newer version and publish it?

**Comment by ysalmon** [comment]
I do not think so : the standard OCaml has an ```-unsafe``` command line parameter for example ; I cannot seem to pass this one either. Modifying the kernel.json accordingly, I get ```/home/yann/.opam/4.07.0/bin/ocaml-jupyter-kernel: unknown option '-unsafe'.```.

**Comment by akabe** [comment]
Of course, OCaml standard parameters can be tested.

`-easytype` option sets `true` to `Clflags.easy_type_errors` variable. However this variable is undefined in the standard `compiler-libs`. I need to generate code that does not access the variable when the standard OCaml compiler like:

```
#ifdef HAVE_EASY_TYPE_ERRORS (* cppo syntax *)
(* code for `-easytype` *)
#endif
```

I want to check detection of `Clflags.easy_type_errors` and code generation for the standard OCaml and the customized one.

**Comment by ysalmon** [comment]
OK, I was not aware that you need to replicate the parts of the code of ocaml that deal with command line options. Thanks for the explanation.

I will see what can be done with Charguéraud's fork, but it will take some time.

**Comment by ysalmon** [comment]
Thank you for keeping in touch on this. But I should have explained what I meant by "some time" : porting Charguéraud's patches to a newer kernel line is not something that I can do myself (I use OCaml but I have never looked into the compiler itself -- I wouldn't have the slightest clue how to rebase correctly) ; I need to get more knowledgeable people to do it and to do so I need to talk them into it. My next opportunity to get things moving is in May.
