### ISSUE TITLE
Running different OCaml versions

### ISSUE THREAD

**Issue by ysalmon** [akabe/ocaml-jupyter#103]
I now have a jupyter kernel for OCaml 4.02.2 and another one for OCaml 4.07.0. They both appear in the Jupyter menu but I seem to be able to run only one of them, depending on which opam switch was active in the environment that launched the jupyter server.

From the error messages in the console, I think this is because of inadequate LDPATH.

This in spite of both kernel JSONs specifying the absolute path to the relevant ocaml-jupyter-kernel and the shebang in them also specifying the absolute path to the relevant ocamlrun.

But the environment is not set.

This could be solved by outputting ```opam env``` as an ```env``` dict in the kernel json. But this might be problematic for the PATH, be cause we want to add the relevant opam path, not replace the whole PATH variable and we cannot know at the time of the generation of kernel.json what will be the PATH variable at execution time.

Another way would be to have in the ocaml-jupyter-kernel shebang a small shell script that would set the environment with ```opam env --switch=XXX``` and then become ocamlrun.

**Comment by akabe** [comment]
Thanks for reporting a bug. I reproduced the problem, and correct environment variables solve it. I will fix the bug.
