### ISSUE TITLE
console use

### ISSUE THREAD

**Issue by nilsbecker** [akabe/ocaml-jupyter#106]
I have been exploring using ocaml-jupyter from the jupyter console. 
(See https://discuss.ocaml.org/t/jupyter-a-better-utop/2633)

It's working pretty well! However a few things could be improved for console use.

- directives. is there a way to get the utop directives to work? ls, cd, pwd, things like that.
- Merlin completion works out of the box but not for ocaml directives such as `#require` and on package names
- Merlin inspection does not seem to work. is this a problem of the console not recognizing shift+tab?

**Comment by akabe** [comment]
Sorry for late reply.

> directives. is there a way to get the utop directives to work? ls, cd, pwd, things like that.

You can add directives by `Toploop.add_directive : string -> directive_fun -> directive_info -> unit` in `compiler-libs.common` and implement a library containing such directives if you need. Directives are not dependent from utop's functionality.

> Merlin completion works out of the box but not for ocaml directives such as #require and on package names

Yes, merlin doesn't support completion for directives. The completion of directives does not seem necessary to me, but merlin team might support it. Please open an issue in the merlin project.

> Merlin inspection does not seem to work. is this a problem of the console not recognizing shift+tab?

Maybe you are right. If inspection fired in console, merlin inspection would work.

**Comment by nilsbecker** [comment]
thanks, it may be really doable to provide a few basic directives by hand. would you be open to a pull request in case i find the time (presently not very likely)?

**Comment by akabe** [comment]
Cool, but I recommend to publish a library including your directives on opam, independent from ocaml-jupyter package. The library might help users of other ocaml REPLs, e.g., the standard `ocaml` command. Actually, I think utop should supply the directives like `#cd` independently from utop.
