### ISSUE TITLE
qtconsole crashes on start

### ISSUE THREAD

**Issue by nilsbecker** [akabe/ocaml-jupyter#107]
i tried `jupyter qtconsole --kernel=ocaml-jupyter` with a kernel that works in the regular console. it fails with:

```
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'kernel_banner' trait of a RichJupyterWidget instance must be a unicode string, but a value of None <class 'NoneType'> was specified.
```
i noticed that when i start the regular jupyter console, `None` is echoed on startup which might have something to do with that.

**Comment by akabe** [comment]
Thanks for reporting the bug. I reproduced the problem and will fix it.
