### ISSUE TITLE
Unable to specify different notebooks directory when using Docker

### ISSUE THREAD

**Issue by j-christl** [akabe/ocaml-jupyter#112]
First of all: Sorry, I am quite new to Docker and the solution probably is trivial.
Both given commands do not provide the option to use a diferent directory for my jupyter notebooks. 

How can I launch the ocaml notebook in my home directory? The "-v" flag does not work for me.
(I am using Mac OSX 10.14.1)

**Comment by akabe** [comment]
Use `--notebook-dir` option like `docker run -v <HOST_DIR>:/notebooks IMAGE jupyter notebook --notebook-dir=/notebooks`.

**Comment by akabe** [comment]
Closed due to no reply. Please re-open this issue if your problem is not solved.
