### ISSUE TITLE
printing to stdout and stderr

### ISSUE THREAD

**Issue by nilsbecker** [akabe/ocaml-jupyter#113]
in an ocaml-jupyter console in the terminal when i try
`print_int 8998;;`
i get no output except for the return value which is `()`. similarly, `Format.(fprintf std_formatter "sdf")` gives no visible output.
it seems that these output channels are swallowed by jupyter somehow?

**Comment by akabe** [comment]
Did you flush stdout?

**Comment by nilsbecker** [comment]
ah right! this prints: `print_int 3234; print_newline ();;` 
however, in utop i don't have to flush manually, it seems to do that automatically. utop's behavior makes sense to me, since it's an interactive session.

**Comment by akabe** [comment]
I don't think it's important. If necessary, please give me a PR.

**Comment by nilsbecker** [comment]
ok, fair enough.

**Comment by nilsbecker** [comment]
ok, i ran into this again and i think it's more serious than i thought. just open an ocaml-jupyter console and to `print_string "sdfsd";;` and then `flush stdout;;`. for me, nothing is printed, also after several times or when using `flush_all ()`. only `print_newline ();;` actually flushes the output.

i now think this is really a bug

**Comment by nilsbecker** [comment]
an additional point: the standard toplevel `ocaml` also flushes automatically after every prompt.
