### ISSUE TITLE
Instalation Problem 

### ISSUE THREAD

**Issue by m50008** [akabe/ocaml-jupyter#114]
Hey, when i try to run the command `opam install iocaml` i get this error 
`The following dependencies couldn't be met:`
 ` - iocaml → iocamljs-kernel >= 0.4.6 → js_of_ocaml < 3.0 → ocaml < 4.05.0
      base of this switch (use --unlock-base to force)`
 ` - iocaml → ocaml < 4.02.0
      base of this switch (use --unlock-base' to force)`

**Comment by akabe** [comment]
This repository is for `ocaml-jupyter`, not `iocaml`. If you want to install `ocaml-jupyter`, try `opam install jupyter`. Otherwise, you open an issue at https://github.com/andrewray/iocaml, maintained by andrewray, not me.
