### ISSUE TITLE
Using the ocaml kernel on colab

### ISSUE THREAD

**Issue by LaurentMazare** [akabe/ocaml-jupyter#121]
Hi, first thanks a lot for all the hard work on this ocaml kernel - this is a very thing to have.

I just wrote a small colab notebook that lets you install this kernel on free colab instances. Once the first cell of this notebook has run, you can run ocaml notebooks othe same colab instance (by default it will use a cpu instance but I was even able to get it to run on a gpu instance and to use ocaml-torch to train an ocaml model on the gpu).

The notebook can be seen [here](https://colab.research.google.com/drive/11l2Fs4NqDj6vHs167BCzjb6woZhhQPEr).

Maybe this would be useful to link to from your repo ? I'm not sure what the easiest way would be to integrate this, perhaps the notebook could be added to your repo and we can have some colab link to it as demonstrated [here](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb). Happy to make a PR for this if you think it's worth it - or to go another way if you have some thoughts.

**Comment by akabe** [comment]
Thanks for great work! This is the easiest way to use ocaml-jupyter kernel. I think a link to your notebook may help users if it is in README. Looking forward to your PR.

**Comment by LaurentMazare** [comment]
Closing now that the PR has been merged, thanks!

**Comment by Naereen** [comment]
Hi @LaurentMazare,
That was a great initiative, thanks!

Is the notebook still working on your side?
I've tried last week, and just tried again...

> Error loading https://apis.google.com/js/client.js
> https://drive.google.com/drive/?action=locate&id=11l2Fs4NqDj6vHs167BCzjb6woZhhQPEr&authuser=0
> Error loading https://apis.google.com/js/client.js
> V/U</h.onerror@https://colab.research.google.com/v2/external/gapi_loader.js:19:330

**Comment by Naereen** [comment]
I would like to point out that another approach, which works on Google Colab (I just tried) is to use your ocaml Pypi package @LaurentMazare !
See https://nbviewer.jupyter.org/github/Naereen/notebooks/tree/master/Demonstration_of_Pypi_package_OCaml_for_polyglot_notebook_02-2021.ipynb
