### ISSUE TITLE
can't install Jupyter

### ISSUE THREAD

**Issue by operade** [akabe/ocaml-jupyter#123]
Hi when I try to install Jupiter with "opal install Jupyter" I have the following message
The following dependencies couldn't be met:
  - jupyter → jbuilder < 1.0+beta18 → ocaml < 4.08.0
      base of this switch (use `--unlock-base' to force)
  - jupyter → lwt < 4.0.0 → ocaml < 4.08.0
      base of this switch (use `--unlock-base' to force)
  - jupyter → ppx_deriving_yojson >= 3.0 → ppx_tools → ocaml < 4.08
      base of this switch (use `--unlock-base' to force)
  - jupyter → ppx_deriving_yojson >= 3.0 → ppx_deriving < 4.3 → ocaml < 4.06.0
      base of this switch (use `--unlock-base' to force)
  - jupyter → ppx_deriving_yojson >= 3.0 → ppx_deriving < 4.3 → ppx_tools >=
    4.02.3 → ocaml < 4.08
      base of this switch (use `--unlock-base' to force)
  - jupyter → ppx_deriving_yojson >= 3.0 → ocaml < 4.05.0
      base of this switch (use `--unlock-base' to force)

No solution found, exiting

It seems that the ocaml version is the problem. Could you please try to fix it ? Thanks

**Comment by mseri** [comment]
Which version of ocaml are you using? `ocaml 4.08.0` has just been released with many breaking changes, multiple packages are still catching up with it (e.g. ppx_deriving)

**Comment by mseri** [comment]
Try also to run `opam update`, the latest `jupyter` uses `dune` but for some reasons your opam is trying to install `jbuilder` instead. You can also try `opam install jupyter --dev` to install the current master branch

**Comment by mseri** [comment]
On a related note: @akabe can you make a release of the latest jupyter? The current release conflicts with the latest `Base64` that I have to use in some packages

**Comment by operade** [comment]
Hi mseri : I have ocaml 4.08.0 and no update are available ; furthermore when I try
opam install jupyter --dev

I get opam: unknown option `--dev', did you mean either `-d' or `--yes' ?
Usage: opam install [OPTION]... [PACKAGES]...
Try `opam install --help' or `opam --help' for more information.

Thanks

**Comment by operade** [comment]
I had a backup of the .opam directory : I restored it  and now Jupyter is back !
