### ISSUE TITLE
Automatic handling of Lwt.t and Async.t

### ISSUE THREAD

**Issue by LaurentMazare** [akabe/ocaml-jupyter#124]
Hello,
utop includes some magic so that top level expressions of types `'a Lwt.t` or `'a Async.t` are transformed into blocking calls that return the underlying `'a`. Maybe it would be nice to support the same kind of thing in the jupyter kernel ?
For what it's worth by copying and pasting [lines 420-580 of uTop_main.ml](https://github.com/ocaml-community/utop/blob/da0fa23a05d5ab466f2098656094c8532cd29ae3/src/lib/uTop_main.ml#L420-L580), I was able to get this to work with very small changes. I'm happy to make a PR out of it if you think that's interesting.

**Comment by mseri** [comment]
I think it would be quite useful

**Comment by akabe** [comment]
Thank your! I'm looking forward to your PR.

**Comment by akabe** [comment]
Close due to #126 is merged
