### ISSUE TITLE
Magic

### ISSUE THREAD

**Issue by scemama** [akabe/ocaml-jupyter#133]
Hello,
first, thank you for developing this project which is very useful!

With the Python kernel, there are "magic" commands starting with the `%` sign (for more info, run `%magic` in a Python kernel).
They have a nice features like `%%html` to render the cell as a block of HTML, `%%latex` to render the cell as a block of latex, or `%%svg` to render the cell as an SVG literal.

Would it be simple to add such functionalities? (I can contribute if needed).

Best,
Anthony

**Comment by akabe** [comment]
sorry for late reply.
the magic commands such as html, latex, etc. can be implemented by calling [Jupyter_notebook.display](https://akabe.github.io/ocaml-jupyter/api/jupyter/Jupyter_notebook/#val-display).
it's easy maybe, but I don't feel importance of the functionalities.
If you send a PR, I will merge it.
