### ISSUE TITLE
Nix/NixOS compatibility; remove installation-time dependency on opam

### ISSUE THREAD

**Issue by kwshi** [akabe/ocaml-jupyter#139]
I am trying to get this to build and work on [Nix](https://nixos.org/nix/)+[NixOS](https://nixos.org/nix/), a "declarative" package manager+operating system with a lot of appeal to the functional programming community.

The existing installation/build process relies on opam to generate and write the Jupyter kernelspec files (`kernel.json`, `kernel.sh`).  This approach is incompatible with Nix, which manages its own OCaml versions/dependencies and does _not_ use opam.  Consequently, when Nix tries to build it like other Dune packages by calling `dune build -p jupyter`, Dune first tries to generate the kernelspec files by calling `config/kernelspec.exe`, which tries to call `opam`, and throws a "command not found" error.

The NixOS-specific fix would be to not generate these kernelspec files at all or at least remove the kernelspec generation script from the default installation step, since NixOS provides its own way of configuring Jupyter to use additional kernels via its [`jupyter` module](https://nixos.org/nixos/options.html#jupyter.kernels).  But I recognize doing so may make the installation process less convenient for others.

Personally, I think it is best if the installation process is package-manager-neutral, i.e. it doesn't assume what OCaml package manager people are using.  Considering that the kernelspec is a Jupyter configuration and is not in any way an actual dependency of the OCaml Jupyter kernel program itself, it makes sense that one should be able to just build the OCaml Jupyter kernel without needing to generate the kernelspec first (NixOS users especially don't need the kernelspec to be generated at all).  Following this reasoning, my suggestion is this:

- Separate the `kernel.{json,sh}` generation from the Dune installation process.  Instead, make `kernelspec.ml` a separate public executable (named something along the lines of `ocaml-jupyter-genspec`) that _may_ rely on `opam` if it needs to and generates the kernelspec files as a _convenience tool only for those who want it_.
- Add instructions in the README, telling users to either manually create the kernelspec files following some example or, for opam users, generate it using `ocaml-jupyter-genspec`.

I believe this is a reasonable compromise: the convenience of auto-generating the kernelspec files remains, but non-opam users won't need to install opam just to build the standalone kernel (opam is only needed for the kernelspec generation), and for opam users there are only 1-2 extra commands to run during installation.

What do you think about this?

**Comment by akabe** [comment]
Thanks. I don't know how popular Nix is. However removing dependency to opam seems good idea. I will remove kernelspec.ml, and add ocaml-jupyter-opam-genspec for manual generation of kernel.json instead.
