### ISSUE TITLE
Graphics Implementation

### ISSUE THREAD

**Issue by jbdoderlein** [akabe/ocaml-jupyter#143]
Hi,
Is there an implementation of the Graphics module in jupyter-ocaml? 
When I try to open a graphic:
```ocaml
#load "graphics.cma";;
open_graph "";
```
I'm getting this error:
```
Exception: Graphics.Graphic_failure "Cannot open display ".
Raised by primitive operation at unknown location
Called from file "toplevel/toploop.ml", line 180, characters 17-56
```

Thank you in advance!

**Comment by akabe** [comment]
No. Graphics module requires a window, while jupyter doesn't have.

Instead, you can draw an image with a third-party graphics package such as cairo2, and embed the image into a notebook by `display` or `display_file` functions in [jupyter.notebook](https://akabe.github.io/ocaml-jupyter/api/jupyter/Jupyter_notebook).

**Comment by akabe** [comment]
This is a simple example: https://github.com/akabe/docker-ocaml-jupyter-datascience/blob/master/notebooks/simple_image_filtering.ipynb

**Comment by Naereen** [comment]
Actually, it could be possible to hack something based on what TryOCaml and js_of_ocaml have done for the Graphics module.
See the "lesson 19" example on [the old version of TryOCaml](https://perso.crans.org/besson/try-ocaml.en.html) (on my website):
![Capture d’écran_2021-02-14_16-28-22](https://user-images.githubusercontent.com/11994719/107880856-b3501900-6ee1-11eb-9af5-96d74f443cf4.png)

But I see many reasons not to spend time on this:
- it wouldn't be easy ;
- it wouldn't be that useful, honestly apart from toy examples I never used the Graphics module for any real purpose.

**Comment by jbdoderlein** [comment]
Thank you very much for your response,

In the end I went back to other solutions (js_of_ocaml). I was mainly looking for a tool that is nice, easy to install and that includes the Nums and Graphics modules for educational purposes. So I decided to code myself a small IDE based on the toplevel of js_of_ocaml ([the repo](https://github.com/jbdo99/BetterOCaml)).
