### ISSUE TITLE
Installation with opam switch

### ISSUE THREAD

**Issue by scemama** [akabe/ocaml-jupyter#144]
Hi, 
I installed the 4.10.0 version of OCaml by doing

    opam switch create 4.10.0

Then I installed jupyter:

    opam install jupyter

At the end of the installation, I got the following message:

```
<><> jupyter.2.7.0 installed successfully <><><><><><><><><><><><><><><><><><><>
=> Please run for registration of ocaml-jupyter kernel:
=>
=> $ ocaml-jupyter-opam-genspec
=> $ jupyter kernelspec install --name ocaml-jupyter \
=> /home/scemama/qp2/external/opam/4.10.0/share/jupyter
```

but the directory  `/home/scemama/qp2/external/opam/4.10.0/share/jupyter` does not exist so the command fails. However, there is a directory named ` /home/scemama/qp2/external/opam/default/share/jupyter` for which the installation works. So there is a little bug in the printed message.

best,
Anthony

**Comment by akabe** [comment]
I think `ocaml-jupyter-opam-genspec` makes the directory, or shows an error message.

**Comment by scemama** [comment]
You are right, my bad. There is no problem.
Thanks
