### ISSUE TITLE
Install instructions say to install archimedes, but it requires old OCaml versions

### ISSUE THREAD

**Issue by philtomson** [akabe/ocaml-jupyter#146]
I'm running 4.10.0, but I noticed this in 4.09.0 as well:

> 
> $ opam reinstall archimedes
> archimedes is not installed. Install it? [Y/n] y
> The following dependencies couldn't be met:
>   - archimedes → camlp4 → ocaml-variants (= 4.02.0+modular-implicits & =
>     4.02.1+modular-implicits-ber)
>       no matching version
>   - archimedes → camlp4 → ocaml < 4.09
>       base of this switch (use `--unlock-base' to force)
>   - archimedes → ocaml < 4.03
>       base of this switch (use `--unlock-base' to force)

If I'm interpreting this correctly you need to be running a version of OCaml less than 4.03 - is that correct?

**Comment by akabe** [comment]
archimedes 0.4.19 supports ocaml 4.03 or above (https://github.com/ocaml/opam-repository/blob/master/packages/archimedes/archimedes.0.4.19/opam). `opam update && opam upgrade` maybe solves your problem. If it does not, you should open an issue on https://github.com/ocaml/opam-repository/ or http://forge.ocamlcore.org/projects/archimedes/
