### ISSUE TITLE
How to set different color of bars by if condition?

### ISSUE THREAD

**Issue by impvd** [akabe/ocaml-jupyter#151]
There're some QAs in matplotlib/python, [refer](https://stackoverflow.com/questions/3832809/how-to-change-the-color-of-a-single-bar-if-condition-is-true-matplotlib), but it seems that the mechanism of Archimedes is different from python world.

I didn't find Archimedes repo in Github, so I created an issue here, let me know if I was wrong.

I was wondering if maybe we could set different color of bars by condition?

A minimal test case would like:

```
#require "graphics";;
#require "jupyter-archimedes"

let rec walk acc p i =
  if i = 0 then List.rev acc else begin
    let q = if Random.bool () then succ p else pred p in
    walk (q :: acc) q (pred i)
  end

let points = List.map float @@ walk [] 0 10

let vp = A.init ~w:560. ~h:260. ["jupyter"] in
A.Axes.box vp ;
A.List.y vp ~style:(`Bars 0.9) ~fillcolor:A.Color.dark_slate_grey ~fill:true points ; 
A.close vp
```

It would look like:

![image](https://user-images.githubusercontent.com/37371804/89115122-ee937900-d4b6-11ea-9279-20dc9e25b45f.png)

For example, I would like to set the bars under `0` using red color.

**Comment by akabe** [comment]
@pivdets Sorry for late reply. I think this is the simplest way:

```ocaml
let rec walk acc p i =
  if i = 0 then List.rev acc else begin
    let q = if Random.bool () then succ p else pred p in
    walk (q :: acc) q (pred i)
  end ;;

let points = List.map float @@ walk [] 0 10 ;;

let vp = A.init ~w:560. ~h:260. ["jupyter"] in
A.Axes.box vp ;
A.List.y vp ~style:(`Bars 0.9) ~fillcolor:A.Color.dark_slate_grey ~fill:true
  (List.map (fun y -> if y < 0.0 then 0.0 else y) points) ;
A.List.y vp ~style:(`Bars 0.9) ~fillcolor:A.Color.red ~fill:true
  (List.map (fun y -> if y > 0.0 then 0.0 else y) points) ;
A.close vp
```
