### ISSUE TITLE
How to set xticks in the plotted graph?

### ISSUE THREAD

**Issue by impvd** [akabe/ocaml-jupyter#152]
After reading [archimedes' API](http://archimedes.forge.ocamlcore.org/API/Archimedes.Array.html#VALy)  , it seems that we could only use integer as xtick.

I was wondering if maybe we could custom the xtick like [matplotlib](https://matplotlib.org/3.1.0/gallery/ticks_and_spines/custom_ticker1.html#sphx-glr-gallery-ticks-and-spines-custom-ticker1-py) ?

![image](https://user-images.githubusercontent.com/37371804/89894434-a5f16380-dc0c-11ea-9de9-ba095de05aad.png)

**Comment by akabe** [comment]
@pivdets This is a short answer:

```ocaml
let points = [1.0; 2.0; 3.0] in
let vp = A.init ~w:560. ~h:260. ["jupyter"] in
A.Axes.y ~grid:true ~tics:A.Tics.(Fixed (Custom (fun y -> Format.sprintf "$%g" y), [1.0; 1.5; 3.0])) vp ;
A.List.y vp ~style:(`Bars 0.9) ~fillcolor:A.Color.dark_slate_grey ~fill:true points ;
A.close vp
```

This question is not directly related to ocaml-jupyter kernel. 
Send e-mails to authors of archimedes library from next time.
