### ISSUE TITLE
Unresolved references found in the documentation

### ISSUE THREAD

**Issue by Naereen** [akabe/ocaml-jupyter#163]
Hello there dear @akabe,
For the first time, I read the [documentation](https://akabe.github.io/ocaml-jupyter/api/jupyter/Jupyter_notebook/#val-printf) for the OCaml modules provided by `ocaml-jupyter`.
This page of the doc has a few "unresolved references" to `Format.printf` and `JupyterNotebook.formatter`:
![Capture d’écran_2021-02-14_16-41-17](https://user-images.githubusercontent.com/11994719/107881208-a8968380-6ee3-11eb-9395-246e919c409b.png)

I've used OCamlDoc a few years ago, but I'm not enough an expert to know how to fix this in the `Jupyter_notebook` module code.

I suspect the first error comes because `Format` module is not included and should be cross-references from [its documentation](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Format.html), but `JupyterNotebook.formatter` might be an error of not using `Jupyter_notebook.formatter` ?

Thanks, regards from France, -- @Naereen

**Comment by akabe** [comment]
Thank you for reporting a problem. `JupyterNotebook` was renamed to `Jupyter_notebook`, but I forget to rewrite the names in a comment. I will fix it.

**Comment by Naereen** [comment]
Thanks :+1:
