### ISSUE TITLE
Problems when I want to require jupyter-archimedes

### ISSUE THREAD

**Issue by Meng-Ziwei** [akabe/ocaml-jupyter#169]
I have finished to install jupyter-archimedes, and you can see the result. 
<img width="562" alt="截屏2021-03-03 16 45 30" src="https://user-images.githubusercontent.com/78152357/109778510-de579e00-7c3f-11eb-8417-e0c1de39d333.png">
However, when I require jupyter-archimedes,  I got `Error: Reference to undefined global `Archimedes'` and I don't know how to solve this.
<img width="721" alt="截屏2021-03-03 16 54 23" src="https://user-images.githubusercontent.com/78152357/109779656-1c08f680-7c41-11eb-9231-5da3c42a1056.png">
Thanks for any suggestions!

**Comment by akabe** [comment]
It seems that binary files of jupyter-archimedes or archimedes_cairo are wrong. Do the following commands solve this problem?

```sh
opam reinstall archimedes
opam reinstall jupyter-archimedes
```

**Comment by eglyph** [comment]
Just FYI I run into exactly this issue. Reinstalling packages didn't work. Upgrading `opam` to latest and creating a new switch for 4.11 (was 4.10) did help.

**Comment by anentropic** [comment]
Same issue for me, on 4.14.0:
```
/Users/anentropic/.opam/oktree/lib/ocaml/unix.cma: loaded
/Users/anentropic/.opam/oktree/lib/ocaml/bigarray.cma: loaded
/Users/anentropic/.opam/oktree/lib/cairo2: added to search path
/Users/anentropic/.opam/oktree/lib/cairo2/cairo2.cma: loaded
/Users/anentropic/.opam/oktree/lib/ocaml/dynlink.cma: loaded
/Users/anentropic/.opam/oktree/lib/ocaml/camlp4: added to search path
/Users/anentropic/.opam/oktree/lib/archimedes: added to search path
/Users/anentropic/.opam/oktree/lib/archimedes/archimedes_internals.cma: loaded
/Users/anentropic/.opam/oktree/lib/archimedes/archimedes_toploop.cma: loaded
Cannot find file graphics.cma.
Exception:
Symtable.Error (Symtable.Unavailable_primitive "caml_gr_text_size").
/Users/anentropic/.opam/oktree/lib/archimedes/archimedes_cairo.cma: loaded
File "[2]", line 1:
Error: Reference to undefined global `Archimedes'
```

Reinstalling doesn't fix it

Also the introduction notebook [here](https://github.com/akabe/ocaml-jupyter/blob/master/notebooks/introduction.ipynb) says `$ opam install -y cairo2 archimedes jupyter` but it should also have `jupyter-archimedes` too

**Comment by anentropic** [comment]
also... it says "[Archimedes](http://archimedes.forge.ocamlcore.org/) is an easy-to-use 2D plotting library"

but I can't find any docs for Archimedes anywhere, which makes it less easy to use

**Comment by anentropic** [comment]
Ok, looks like the problem is "Cannot find file graphics.cma."

additional step is needed since OCaml 4.09 https://github.com/ocaml/ocaml/issues/9472#issuecomment-616103606


```
#require "graphics"
#require "jupyter-archimedes"
```

after that it works, nice! 👍

**Comment by akabe** [comment]
@anentropic Thank you. I'll fix notebooks/introduction.ipynb

> also... it says "[Archimedes](http://archimedes.forge.ocamlcore.org/) is an easy-to-use 2D plotting library"
> but I can't find any docs for Archimedes anywhere, which makes it less easy to use

Hmm.  I think an api documentation of archimedes was anywhere, but I cannot find it now.
