### ISSUE TITLE
`#trace` directive not working

### ISSUE THREAD

**Issue by TheyCallMeHacked** [akabe/ocaml-jupyter#181]
Hi, it seems like the `#trace` directive hasn't been implemented in the kernel. Running `#trace f` yields an `unknown directive` exception. The directive works perfectly fine on the default OCaml toplevel.

**Comment by Camil11** [comment]
I got the same error, and it appears on my Ocaml 4.13.1 version kernel, but not in my Ocaml 4.08.1 version kernel.

**Comment by akabe** [comment]
Thanks for reporting.
Solving this problem probably takes a time because I cannot imagine its cause now.
Please give me a time.

**Comment by TheyCallMeHacked** [comment]
Of course

**Comment by akabe** [comment]
#182 solves the problem.
