### ISSUE TITLE
keranal is not starting in juyoiter network

### ISSUE THREAD

**Issue by priyanshujiiii** [akabe/ocaml-jupyter#191]
how to add ocaml kernel in jupuiter notebook.

**Comment by mseri** [comment]
There is a post-installation message that tells you how to install the kernel.
It usually requires you to call
```
ocaml-jupyter-opam-genspec
jupyter kernelspec install --user --name "ocaml-jupyter-$(opam var switch)" "$(opam var share)/jupyter"
```
The readme provides more details.

**Comment by akabe** [comment]
Sorry for very late reply. I close this issue because it seems solved.
@mseri Thank you for supporting!
