### ISSUE TITLE
here its showing the error installing jypyter notebook.

### ISSUE THREAD

**Issue by priyanshujiiii** [akabe/ocaml-jupyter#192]
+- The following actions failed
| - build conf-gmp        4
| - build conf-pkg-config 2
+-
+- The following changes have been performed (the rest was aborted)
| - install base                v0.15.0
| - install base64              3.5.0
| - install dune-configurator   3.4.1
| - install logs                0.7.0
| - install lwt                 5.6.1
| - install lwt_ppx             2.1.0
| - install ocaml-compiler-libs v0.12.4
| - install ocamlbuild          0.14.1
| - install ocplib-endian       1.2
| - install octavius            1.2.2
| - install ppx_derivers        1.2.1
| - install ppx_deriving        5.2.1
| - install ppx_js_style        v0.15.0
| - install ppx_yojson_conv     v0.15.0
| - install ppx_yojson_conv_lib v0.15.0
| - install ppxlib              0.26.0
| - install result              1.5
| - install sexplib0            v0.15.1
| - install stdint              0.7.0
| - install stdlib-shims        0.3.0
| - install topkg               1.0.5
| - install uuidm               0.9.8
+-

The packages you requested declare the following system dependencies. Please make sure they are installed before retrying:
    gmp system:pkgconf

The former state can be restored with:
    C:\OCaml64\usr\local\bin\opam.exe switch import "C:/OCaml64/home/india/.opam/4.14.0+mingw64c/.opam-switch/backup/state-20220913125828.export"

its showing this error.

**Comment by mseri** [comment]
You need to install those two dependencies (gmp and pkgconf), usually one does it with `opam depext jupyter` but I don't know if/how this works on windows.

**Comment by akabe** [comment]
Sorry for very late reply. I have the same opinion as @mseri .
I don't know how to install ocaml jupyter kernel on windows because I have not tried that.
I close this issue due to no progess.
If you still try to install ocaml jupyter kernel on windows, please re-open or create a new issue.
