### ISSUE TITLE
Add comparison to simple_jucaml

### ISSUE THREAD

**Issue by slel** [akabe/ocaml-jupyter#49]
The frontpage for OCaml Jupyter (and the README in this repo)
include a feature comparison table to IOCaml.
It would be nice to include simple_jucaml in this table.
https://github.com/KKostya/simple_jucaml

**Comment by akabe** [comment]
I think it's not important. Is simple_jucaml developed for practical purpose? It seems simple_jucaml is a too simple program, as its name suggests. I wrote the comparison table with IOCaml for preventing new users from confusing which they should use. I guess they can understand that ocaml-jupyter is more practical than simple_jucaml.

**Comment by slel** [comment]
Then maybe just mention simple_jucaml in the "Related work" section.

Another related work that could be mentioned is the following library for writing
jupyter kernels in OCaml: https://github.com/ocaml-jupyter/jupyter-kernel

**Comment by akabe** [comment]
OK. Thank you for telling me similar programs.

**Comment by akabe** [comment]
@slel Do you have any comment? https://github.com/akabe/ocaml-jupyter/pull/51
