### ISSUE TITLE
Output from multiple cells are not displayed correctly

### ISSUE THREAD

**Issue by Naereen** [akabe/ocaml-jupyter#54]
Hi again,
Everything seems to work fine, but I found a weird behavior, possibly a bug.

When I hit "Run all cells", or "All above" or "All below", or select multiple cells and execute them, only the last one shows the output from *all* the executed cells.
I think this is a bug, could you try to reproduce it? It seems to occur for long running cells (more than 1 seconds).

See this example, the first 2 cells are correctly executed, the next 2 are executed while being jointly selected, and the output are merged and online displayed for the 2nd cell:
![gifrecord_2017-09-13_202326](https://user-images.githubusercontent.com/11994719/30393851-a7d4e424-98c1-11e7-9f06-fc9d5486c2ae.gif)

It shouldn't be too hard to fix, the kernel server is probably keeping a buffer of its output (received by the notebook) and the buffer is not flushed as often as it should be...

**Comment by akabe** [comment]
I reproduced it when the upper cells takes execution time. I will try to fix at this weekend. Thanks for reporting the bug.

**Comment by Naereen** [comment]
@akabe OK, I am glad it is reproducible.
Good luck (I will totally be unable to help for the next few weeks, sorry).

**Comment by akabe** [comment]
I fixed this bug faster than I thought!
