### ISSUE TITLE
Add this kernel on https://github.com/jupyter/jupyter/wiki/Jupyter-kernels

### ISSUE THREAD

**Issue by Naereen** [akabe/ocaml-jupyter#72]
IOCaml is listed but not ocaml-jupyter.
It would make more sense if you did the issue or PR, what do you think?

**Comment by akabe** [comment]
Thanks for telling. It seems good to me. I will do it!

**Comment by akabe** [comment]
I can edit the page without PR and reviews. I added.

**Comment by Naereen** [comment]
Great!
