### ISSUE TITLE
Update Jupyter_notebook to JupyterNotebook in examples?

### ISSUE THREAD

**Issue by Naereen** [akabe/ocaml-jupyter#81]
In [this example](https://github.com/akabe/ocaml-jupyter/blob/master/notebooks/introduction.ipynb), the Jupyter notebook module is imported and used as `Jupyter_notebook`.
However, after a fresh install, I have it under `JupyterNotebook`:
![jupyternotebook](https://user-images.githubusercontent.com/11994719/33832384-404820ae-de7c-11e7-8850-9eff89ce28dd.png)
Could the example be updated accordingly if this is the expected behavior?
Thanks.

**Comment by akabe** [comment]
Is the version of ocaml-jupyter latest?
See https://github.com/akabe/ocaml-jupyter/releases/tag/v2.0.0 for details.

**Comment by Naereen** [comment]
Damn, I didn't upgrade my package before checking this!

**Comment by Naereen** [comment]
Sorry!

**Comment by akabe** [comment]
Never mind.
