### ISSUE TITLE
Weird display issue for val in stdout with _ (_ not displayed)

### ISSUE THREAD

**Issue by Naereen** [akabe/ocaml-jupyter#83]
Hi! 🎉 Merry new year!

Here is an example of a weird display issue:
![bug_display_out_value_with_underscore_in_its_name](https://user-images.githubusercontent.com/11994719/34725551-91c1feaa-f551-11e7-92dc-cef9a4bf301e.png)
(The variable `ex1_1` but displayed `ex1 1`. On Firefox 57, Ubuntu 17.10)

It's a bug probably coming from the style in `outputarea.less:96`.
I can fix it by forcing a `padding-bottom: 1px;` rule for `div.output_area pre`:
![bug_display_out_value_with_underscore_in_its_name2](https://user-images.githubusercontent.com/11994719/34725685-fa6d5120-f551-11e7-8542-63dfbe2f9352.png)

I will submit the PR to fix this.

**Comment by Naereen** [comment]
Oh, actually the issue is in Jupyter notebook
https://github.com/jupyter/notebook/blob/179bb24fbf79d153812858126127a91431da3319/notebook/static/notebook/less/outputarea.less#L96

See for instance 
![bug_display_out_value_with_underscore](https://user-images.githubusercontent.com/11994719/34725968-ebded114-f552-11e7-9f19-d94e406fc2cd.png)

**Comment by Naereen** [comment]
https://github.com/jupyter/notebook/issues/3193

**Comment by Naereen** [comment]
I think it has nothing to do with ocaml-jupyter, closing.

**Comment by akabe** [comment]
Thanks for reporting the issue!

**Comment by Naereen** [comment]
My PR was accepted in `jupyter/notebook` so in the next 5.3 version it should be fixed.

**Comment by akabe** [comment]
Great! Thank you.

**Comment by Naereen** [comment]
https://github.com/jupyter/notebook/pull/3194
