### ISSUE TITLE
the merlin server requires .merlin path to be absolute 

### ISSUE THREAD

**Issue by ghennequin** [akabe/ocaml-jupyter#93]
In the current setting of `ocaml-jupyter`, the `.merlin` file is completely ignored. This is because the server mode of `merlin` requires an absolute path to the `.merlin` file. For example, try:

```
cd ~/test   # assuming that there's a valid .merlin in there
echo " " | ocamlmerlin single check-configuration -dot-merlin .merlin   # this works
echo " " | ocamlmerlin server check-configuration -dot-merlin .merlin # this doesn't
echo " " | ocamlmerlin server check-configuration -dot-merlin ~/test/.merlin # this works again
```

I guess there must be a good reason for that. Not sure what the best fix is, at the moment I'm simply adding a `"--dot-merlin", "~/test/.merlin"` pair in my `/usr/local/share/jupyter/kernels/ocaml-jupyter/kernel.json`, but this is bad... Alternatively, is there a way of providing a project-specific `kernel.json` file?

**Comment by akabe** [comment]
Thanks for reporting a bug. I think single mode of merlin solves this problem, isn't it?

> Alternatively, is there a way of providing a project-specific kernel.json file?

kernel.json is definition of a kernel, so that we cannot provide a project-specific kernel.json.

**Comment by ghennequin** [comment]
Yes, but I think the server mode was introduced to facilitate synchronisation with IDEs, so we should probably stick to it. I have solved this temporarily by changing `create` in `merlin.ml` to read like so:

```ocaml
let create ?(server = true) ?(bin_path = "ocamlmerlin") ?(dot_merlin = ".merlin") () =
  let dot_merlin = Sys.getenv "PWD" ^ "/" ^ dot_merlin in
  { server; bin_path; dot_merlin; context = Buffer.create 16; }
```

**Comment by akabe** [comment]
Cool. It completely solves this problem. However I don't know synchronization with IDEs. Could you tell me concretely?

**Comment by ghennequin** [comment]
Euh, I don't know much either. This might be helpful:
https://github.com/ocaml/merlin/blob/master/doc/dev/PROTOCOL.md
I know e.g. that vim calls merlin in server mode; I'm thinking that this is what you need when you want to continually feed "context" to merlin, e.g. when you `open Printf` then merlin knows you've done that and can autocomplete `prin` into `printf` (??); if you were to work in "single mode", wouldn't you have to pass the whole history somehow?
